name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  buildpack:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
      - name: Build
        run: |
          pack build kupofdev/coffee-api:latest --builder paketobuildpacks/builder:tiny
      - name: Push
        run: docker push kupofdev/coffee-api:latest